Feature/Server: product 메인 화면 api, product 등록 구현 완료
woowa-techcamp-2021/deal-11 pull request #24
Opened 2021-07-14 09:01 UTC by junbeomAn

- 상품 메인화면 접속 시 모든 상품 중 15개만 불러오도록 구현
- 상품 등록 시 여러가지 텍스트 정보와 이미지 등록 가능하도록 구현

2021-07-14 10:07 UTC, jiyong1 requested changes
product router 리뷰 확인 부탁드립니다 !

2021-07-14 10:07 UTC, jiyong1 commented on server/routes/product/index.js
> +  const query = `SELECT * FROM PRODUCTS LIMIT 15`;
나중에 프론트에서 pagination 생각하면 query로 offset숫자를 받아서 offset을 포함해주는 것도 좋을 것 같아요 ㅎㅎ
쿼리에 offset에 내용없으면 그냥 0부터 시작하도록 해도 되고요 !!

2021-07-14 10:07 UTC, jiyong1 commented on server/routes/product/index.js
> +router.post('/new', upload.array('product-images'), (req, res) => {
all, new라는 url이 필요하지 않을 것 같은데요 ?!
그냥 get이냐 post냐에 따라서 구분해도 될 것 같아요ㅎㅎ

2021-07-14 10:07 UTC, jiyong1 commented on server/routes/product/index.js
> +  const query = `SELECT * FROM PRODUCTS LIMIT 15`;
아 그리고 쿼리로 카테고리도 받으면 좋을 것 같네요 ㅎㅎ

2021-07-14 10:16 UTC, junbeomAn commented on server/routes/product/index.js
> +router.post('/new', upload.array('product-images'), (req, res) => {
api 사용시에 조금 알아보기 편하지 않을까 싶어했는데 그럼 get, post '/'  로 바꾸는게 좋을까요?

2021-07-14 10:17 UTC, junbeomAn commented on server/routes/product/index.js
> +  const query = `SELECT * FROM PRODUCTS LIMIT 15`;
카테고리는 같이 포함되서 올겁니다!
페이지네이션 부분은 조금 고민해봐야겠네요

2021-07-14 10:42 UTC, junbeomAn commented on server/routes/product/index.js
> +  const query = `SELECT * FROM PRODUCTS LIMIT 15`;
카테고리 이름을 보내달라는 말씀이신가보네요..!

2021-07-15 01:35 UTC, jiyong1 commented
점심에 erd 다시 짜겠습니다 !

2021-07-15 01:35 UTC, merged